### ISSUE TITLE
'helm monitor' returns `no such file or directory` error

### ISSUE THREAD

**Issue by wehappyfew** [ContainerSolutions/helm-monitor#1]
Hi, I am trying to use the plugin but I get the following error. 

```
$ helm plugin install https://github.com/ContainerSolutions/helm-monitor
/usr/bin/wget
Connecting to github.com (192.30.253.112:443)
Connecting to github-production-release-asset-2e65be.s3.amazonaws.com (52.216.224.32:443)
helm-monitor_linux_0   8% |**                             |   339k  0:00:11 ETA
helm-monitor_linux_0  38% |***********                    |  1597k  0:00:03 ETA
helm-monitor_linux_0 100% |*******************************|  4179k  0:00:00 ETA
```

```
Installed plugin: monitor
$ helm monitor
Error: fork/exec /root/.helm/plugins/helm-monitor/helm-monitor: no such file or directory
```

I try `mkdir -p /root/.helm/plugins/helm-monitor/helm-monitor` but I get
`mkdir: can't create directory '/root/.helm/plugins/helm-monitor/helm-monitor': File exists`

The container I try to do the above is based on alpine:latest .

Any help would be appreciated!

**Comment by etiennetremel** [comment]
Hi @wehappyfew,

Thanks for reporting this issue.

The `-L` flag was missing on the curl command which is used when run through Alpine, I update the install.sh script and released a new v0.1.1 version: https://github.com/ContainerSolutions/helm-monitor/commit/8ce3a46ad5c88ffa1f864e498a8c40b7c27c03b9

Could you confirm this is now working?

**Comment by wehappyfew** [comment]
Unfortunately no.
I can see that it installs the updated version but the error remains the same.
Did you test it with any particular version of Alpine? I just use `FROM alpine` in my dockerfile.

```
$ cat /root/.helm/plugins/helm-monitor/plugin.yaml
---
name: "monitor"
version: "0.1.1"
usage: "monitor and rollback in case of failure based on metrics or logs"
description: |-
  Query at a given interval a Prometheus or ElasticSearch instance, a rollback
  of the release is initiated if the number of item from the result is positive.
ignoreFlags: false
useTunnel: true
command: "$HELM_PLUGIN_DIR/helm-monitor"
hooks:
  install: "$HELM_PLUGIN_DIR/install.sh"
$ helm monitor
Error: fork/exec /root/.helm/plugins/helm-monitor/helm-monitor: no such file or directory
```

**Comment by etiennetremel** [comment]
With Alpine you need to create build your own binary, here is a working version:

```
FROM golang:1.9-alpine AS build
RUN apk --no-cache add ca-certificates curl git && \
  go get -u github.com/golang/dep/cmd/dep && \
  mkdir -p $GOPATH/src/github.com/ContainerSolutions && \
  curl -L https://github.com/ContainerSolutions/helm-monitor/archive/master.zip -o $GOPATH/src/github.com/ContainerSolutions/helm-monitor.zip && \
  cd $GOPATH/src/github.com/ContainerSolutions && \
  unzip helm-monitor.zip && \
  mv helm-monitor-master helm-monitor && \
  cd helm-monitor &&\
  dep ensure && \
  CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o helm-monitor ./cmd/...

FROM alpine:3.7

ENV HELM_VERSION=v2.8.1

RUN apk --no-cache add git curl

RUN curl -L https://storage.googleapis.com/kubernetes-helm/helm-${HELM_VERSION}-linux-amd64.tar.gz -o helm-${HELM_VERSION}-linux-amd64.tar.gz \
  && tar -xvf helm-${HELM_VERSION}-linux-amd64.tar.gz \
  && mv linux-amd64/helm /usr/local/bin \
  && rm -rf linux-amd64 helm-${HELM_VERSION}-linux-amd64.tar.gz \
  && chmod +x /usr/local/bin/helm && \
  && helm init --client-only && \
  && mkdir -p /root/.helm/plugins/helm-monitor

COPY --from=build /go/src/github.com/ContainerSolutions/helm-monitor/plugin.yaml /root/.helm/plugins/helm-monitor/plugin.yaml
COPY --from=build /go/src/github.com/ContainerSolutions/helm-monitor/helm-monitor /root/.helm/plugins/helm-monitor/helm-monitor

ENTRYPOINT helm
```

**Comment by wehappyfew** [comment]
Hi Etienne, 
I made it work using your dockerfile.
[ ..with a couple of changes 
`./cmd/...` -> `./cmd/` and 
`/usr/local/bin/helm && \` -> `/usr/local/bin/helm \` and 
`--client-only && \` -> `--client-only \` ]

Moreover, I get this output
```
$ helm monitor prometheus --prometheus=http://prometheus-server ${release_name} --verbose --timeout 60 'rate(http_requests_total{code=~"^2.*$"}[1m]) > 0'
Monitoring samplepython-master...
[debug] Processing URL http://ariadne-prometheus-server/api/v1/query?query=rate%28http_requests_total%7Bcode%3D~%22%5E2.%2A%24%22%7D%5B1m%5D%29+%3E+0
[debug] Response: &{{[]}}
[debug] Result count: 0
[..............................................................]
[debug] Result count: 0
[debug] Quitting...
```

As you can see I changed the code to check [to 200] and checking it for one minute.
I just started working with PromQL and maybe I make some mistake, but shouldn't it respond differently?
Would you be able to provide some output example?
Thanks!

**Comment by wehappyfew** [comment]
I am also trying the following

```
$ helm monitor prometheus --prometheus=http://prometheus-server ${release_name} --verbose --timeout 10 'sum(kube_pod_container_status_ready{container="samplepython-master"}) != 1'
Monitoring samplepython-master...
No results after 10 second(s)
[debug] Processing URL http://prometheus-server/api/v1/query?query=sum%28kube_pod_container_status_ready%7Bcontainer%3D%22samplepython-master%22%7D%29+%21%3D+1
[debug] Response: &{{[{}]}}
[debug] Result count: 1
Failure detected, rolling back...
Successfully rolled back to previous revision!
```

I instruct it to rollback only if the sum is not 1, yet it returns count=1 and makes the rollback.

also, I tried it with `>= 0`

$ helm monitor prometheus --dry-run --prometheus=http://prometheus-server ${release_name} --verbose --timeout 20 'sum(kube_pod_container_status_ready{container="samplepython-master"}) >= 0'
Monitoring samplepython-master...
[debug] Processing URL http://prometheus-server/api/v1/query?query=sum%28kube_pod_container_status_ready%7Bcontainer%3D%22samplepython-master%22%7D%29+%3E%3D+0
[debug] Response: &{{[{}]}}
[debug] Result count: 1
Failure detected, rolling back...
Successfully rolled back to previous revision!

with the same results. 
I also added `--dry-run` but it seems to ignore it.

Am I doing something wrong ?? 
Thanks!

**Comment by etiennetremel** [comment]
Sorry @wehappyfew I missed that notification.

What you are doing seems correct.

The result returned contains an object `{}`, so result length > 0, that could explain the rollback decision procedure. I need to investigate this further. Maybe an additional flag to verify against the expected number of result can be added.
I will look at this over the weekend and come back to you.

**Comment by etiennetremel** [comment]
I'm having difficulty to understand what you are trying to achieve with:
```
sum(kube_pod_container_status_ready{container="samplepython-master"}) >= 0
```

This query can be translated:

> if the total amount of samplepython-master container from any pod are ready, then rollback 

Maybe, what you are looking for is rollback the release if the new version of the container restart:
```
sum(kube_pod_container_status_restarts_total{container="samplepython-master", version="2.0.0"}) > 0
```

Does that help?

**Comment by etiennetremel** [comment]
The check is done on how many results are returned, see https://github.com/ContainerSolutions/helm-monitor/blob/master/cmd/monitor_prometheus.go#L134
